language: node_js
node_js:
- 6.11.3

# setup for deployment
addons:
  ssh_known_hosts: cruciblemud.com
before_install:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out deploy_rsa -d

# run tests
before_script:
- npm install
cache:
  directories:
  - node_modules
script: node_modules/jasmine/bin/jasmine.js

# decrypt deployment key
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

# deploy and restart server
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@cruciblemud.com:/root/mud && ssh root@cruciblemud.com '/root/mud/node_modules/forever/bin/forever restartall'
  on:
    branch: master
