language: node_js
node_js:
- 9.8.0
addons:
  ssh_known_hosts: cruciblemud.com
before_install:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
- npm install --production # This may be the default, check this
cache:
  directories:
  - node_modules
script: node_modules/jest/bin/jest.js
before_deploy:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/ root@cruciblemud.com:/root/develop && ssh root@cruciblemud.com '/usr/local/lib/nodejs/node-v9.8.0/bin/forever restart ~/develop/src/server.js'
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/ root@cruciblemud.com:/root/mud && ssh root@cruciblemud.com '/usr/local/lib/nodejs/node-v9.8.0/bin/forever restart ~/mud/src/server.js'
    on:
      branch: master
