language: node_js
node_js:
- 6.11.3
before_install:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
- npm install
cache:
  directories:
  - node_modules
script: node_modules/jasmine/bin/jasmine.js
