language: node_js
node_js:
- 14.15.0
addons:
  ssh_known_hosts: cruciblemud.com
before_install:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
cache:
  directories:
  - node_modules
script:
- npm test && npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/dist/ root@cruciblemud.com:/root/dev && ssh root@cruciblemud.com '~/startdev.sh'
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync -am --stats --delete-after $TRAVIS_BUILD_DIR/dist/ root@cruciblemud.com:/root/prod && ssh root@cruciblemud.com '~/startprod.sh'
    on:
      branch: master
