language: node_js
node_js:
- 9.8.0
addons:
  ssh_known_hosts: cruciblemud.com
before_install:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
- npm install
cache:
  directories:
  - node_modules
script: node_modules/jasmine/bin/jasmine.js
before_deploy:
- openssl aes-256-cbc -K $encrypted_6609cbccfb5a_key -iv $encrypted_6609cbccfb5a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r -v --delete-after --quiet $TRAVIS_BUILD_DIR/ root@cruciblemud.com:/root/develop && ssh root@cruciblemud.com '~/forever restart ~/develop/server.js'
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync -r -v --delete-after --quiet $TRAVIS_BUILD_DIR/ root@cruciblemud.com:/root/mud && ssh root@cruciblemud.com '~/forever restart ~/mud/server.js'
    on:
      branch: master
